### ISSUE TITLE
Installing issues in Linux enviroment

### ISSUE THREAD

**Issue by cesarforteslima** [danjlawson/mixChecker#2]
R
> library(devtools)
> install_github("danjlawson/badMIXTURE")
Downloading GitHub repo danjlawson/badMIXTURE@master
✔  checking for file ‘/tmp/RtmpyqKLZr/remotes64fd3a8f313/danjlawson-badMIXTURE-a4bfdf5/DESCRIPTION’ ...
   cp: cannot stat 'danjlawson-badMIXTURE-a4bfdf5/inst/ReadMe.md': No such file or directory
    ERROR
   copying to build directory failed
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error

# Also when I'm using:
> remotes::install_github("git@github.com:danjlawson/badMIXTURE.git")
Downloading GitHub repo danjlawson/badMIXTURE@master
✔  checking for file ‘/tmp/RtmpyqKLZr/remotes64fd1477f836/danjlawson-badMIXTURE-a4bfdf5/DESCRIPTION’ ...
   cp: cannot stat 'danjlawson-badMIXTURE-a4bfdf5/inst/ReadMe.md': No such file or directory
    ERROR
   copying to build directory failed
Error in run(bin, args = real_cmdargs, stdout_line_callback = real_callback(stdout),  : 
  System command error

Thanks ins advance.

**Comment by danjlawson** [comment]
This was due to a symlink created by using R to create the package via roxygen2 in OSX. The symlink was not linux compatible. Replacing the symlink with a copy solves this problem, now committed.
